CREATE TABLE users (
  id IDENTITY PRIMARY KEY,
  name VARCHAR NOT NULL
);
CREATE TABLE matches (
  id IDENTITY PRIMARY KEY,
  user1 INTEGER NOT NULL,
  user2 INTEGER NOT NULL,
  user1Hand VARCHAR NOT NULL,
  user2Hand VARCHAR NOT NULL
);
